volumes:
  db-storage:

services:
  db:
    image: postgres:16
    env_file:
      - ./API/.env
    volumes:
      - db-storage:/var/lib/postgresql/data

  backend:
    build: ./API/
    depends_on:
      - db

  gateaway:
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - backend