volumes:
  db-storage:
  static:

services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - db-storage:/var/lib/postgresql/data

  backend:
    build: ./API/
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./data:/API/app/data

  frontend:
    build: ./frontend/
    volumes:
      - static:/frontend/dist

  gateaway:
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles