networks:
  network:
    driver: bridge

volumes:
  db-storage:
  static:

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - db-storage:/var/lib/postgresql/data
    networks:
      - network

  backend:
    image: tealord/investments-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./data:/API/app/data
    networks:
      - network

  frontend:
    image: tealord/investments-frontend
    restart: "no"
    volumes:
      - static:/frontend/dist

  gateaway:
    image: tealord/investments-nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles
    networks:
      - network